### ISSUE TITLE
mac version not launching

### ISSUE THREAD

**Issue by drmjc** [panogram/panogram#3]
Hi,
panogram launched great on my mac, but not on a colleagues. I've attached a screenshot. My guess is that as he's not a programmer, he's missing a dependency which your dev team, and myself did have on our local machines?

cheers,
Mark

![screen shot 2014-10-28 at 1 31 52 pm](https://cloud.githubusercontent.com/assets/591923/4803265/d783c942-5e54-11e4-9a22-a8913260e93c.png)

**Comment by andrej-griniuk** [comment]
Hi Mark,

Sorry to hear it's not working on you colleagues machine. What version of Mac OS he is running? Has he tried the previous release? It's a bit hard for me to test, because I'm Windows user, but it worked on both 2 macs I've tried. Anyway, will do my best to get it fixed!

Cheers,
Andrej

**Comment by nicholasblackburn** [comment]
Hi there

I'm running Mac OS X 10.9.5 and i'm getting the same problem. Previous release worked without problems.

Additionally Firefox web app is fine, Safari not so much. 

Cheers,

Nick

**Comment by andrej-griniuk** [comment]
Hi Nick,

seems to be my fault. Uploaded an update, could you try now?
https://github.com/panogram/panogram/releases/download/0.1.2/panogram-0_1_2-macos.zip

Cheers,
Andrej

**Comment by nicholasblackburn** [comment]
Works now :-) Thanks!
